# Generated by Django 5.0.6 on 2026-07-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='jshshr',
            field=models.BigIntegerField(help_text='Namuna: 29572006200016', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.IntegerField(help_text='Namuna: 2275679', unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_serie',
            field=models.CharField(help_text='Namuna: AB', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(help_text='Namuna: 998909009090', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='jshshr',
            field=models.BigIntegerField(help_text='Namuna: 29572006200016', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.IntegerField(help_text='Namuna: 2275679', unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_serie',
            field=models.CharField(help_text='Namuna: AB', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Namuna: 998909009090', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('mechanic', 'Mexanik'), ('instructor', 'Instruktor'), ('coordinator', 'Kordinator')], default='coordinator', max_length=20),
        ),
    ]
