# Generated by Django 5.0.6 on 2026-07-14 06:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_add_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('enrolled', 'Qabul qilingan'), ('finished', 'Tugatgan')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('enrolled', 'Qabul qilingan'), ('finished', 'Tugatgan'), ('canceled', 'Bekor qilingan')], default='enrolled', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='management.category')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='management.student')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'db_table': 'enrollment',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('accepted', 'Qabul qilingan'), ('returned', 'Qaytarilgan'), ('paid', "To'langan")], default='accepted', max_length=20)),
                ('method', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('qr_code', 'QR code'), ('transfer', "O'tkazma")], default='cash', max_length=20)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='management.student')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'db_table': 'payment',
            },
        ),
    ]
