# Generated by Django 5.0.6 on 2026-07-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_student_status_enrollment_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passport_serie',
            field=models.CharField(help_text='Namuna: AB', max_length=2),
        ),
    ]
