# Generated by Django 5.0.6 on 2026-07-14 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_alter_student_passport_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_serie',
            field=models.CharField(help_text='Namuna: AB', max_length=2),
        ),
    ]
