# Generated by Django 5.0.6 on 2026-07-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_user_passport_serie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='jshshr',
            field=models.BigIntegerField(help_text='Namuna: 29572006200016'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passport_number',
            field=models.IntegerField(help_text='Namuna: 2275679'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(help_text='Namuna: 998909009090', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='jshshr',
            field=models.BigIntegerField(help_text='Namuna: 29572006200016'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.IntegerField(help_text='Namuna: 2275679'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(help_text='Namuna: 998909009090', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('phone', 'jshshr')},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('phone', 'jshshr')},
        ),
    ]
