# Generated by Django 5.0.6 on 2026-07-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_student_jshshr_alter_student_passport_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_free',
            field=models.BooleanField(default=False, help_text="Bepul o'qish (grant yoki boshqa imtiyoz)"),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True),
        ),
    ]
