# Generated by Django 5.0.6 on 2026-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_category_notes_enrollment_enrolled_free_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('enrolled', 'Qabul qilingan'), ('finished', 'Tugatgan'), ('canceled', 'Bekor qilingan')], default='enrolled', max_length=20),
        ),
    ]
