# Generated by Django 5.0.6 on 2026-07-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_enrollment_category_alter_enrollment_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_amount',
            field=models.PositiveIntegerField(blank=True, help_text='Shartnoma summasi', null=True),
        ),
    ]
