# Generated by Django 5.0.6 on 2026-07-15 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_enrollment_enrolled_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='student',
        ),
        migrations.AddField(
            model_name='payment',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='management.enrollment'),
        ),
    ]
