# Generated by Django 5.0.6 on 2026-07-16 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_remove_payment_student_payment_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='duration',
            field=models.FloatField(blank=True, help_text='Davomiyligi (oylar, masalan, 3.5 yoki 4)', null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='coordinator',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'coordinator'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinator_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('name', models.CharField(help_text='Guruh nomi', max_length=100)),
                ('started_at', models.DateField(blank=True, help_text='Boshlanish sanasi', null=True)),
                ('duration', models.FloatField(blank=True, help_text='Davomiyligi (oylar, masalan, 3.5 yoki 4)', null=True)),
                ('status', models.CharField(choices=[('started', 'Boshlangan'), ('finished', 'Tugatgan'), ('canceled', 'Bekor qilingan')], default='started', max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='management.category')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'db_table': 'group',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='management.group'),
        ),
    ]
