# Generated by Django 5.0.6 on 2026-07-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_category_duration_enrollment_coordinator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, help_text="Qo'shimcha telefon raqami (namuna: 998909009090)", max_length=20, null=True),
        ),
    ]
