# Generated by Django 5.0.6 on 2026-07-18 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_student_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jshshr',
            field=models.BigIntegerField(blank=True, help_text='Namuna: 29572006200016', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.IntegerField(blank=True, help_text='Namuna: 2275679', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_serie',
            field=models.CharField(blank=True, help_text='Namuna: AB', max_length=2, null=True),
        ),
    ]
