# Generated by Django 5.0.6 on 2026-07-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_user_jshshr_alter_user_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jshshr',
            field=models.BigIntegerField(blank=True, help_text='Namuna: 29572006200016', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_number',
            field=models.IntegerField(blank=True, help_text='Namuna: 2275679', null=True, unique=True),
        ),
    ]
