# Generated by Django 5.0.6 on 2026-07-18 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_user_jshshr_alter_user_passport_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
