# Generated by Django 5.0.6 on 2026-07-18 05:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_user_jshshr_alter_user_passport_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('place_name', models.CharField(help_text="O'quv joyi nomi", max_length=255)),
            ],
            options={
                'verbose_name': 'Learning Place',
                'verbose_name_plural': 'Learning Places',
                'db_table': 'learning_place',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='learning_days',
            field=models.CharField(blank=True, choices=[('Mo-Wed-Fri', 'Mo-Wed-Fri'), ('Tue-Thu-Sat', 'Tue-Thu-Sat'), ('everyday', 'Everyday')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='learning_time',
            field=models.CharField(blank=True, help_text='Masalan: 09:00', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('enrolled', 'Yozilgan'), ('graduated', 'Bitirgan'), ('cancelled', 'Bekor qilingan')], default='enrolled', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='learning_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='management.learningplace'),
        ),
    ]
