# Generated by Django 5.0.6 on 2026-07-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_learningplace_enrollment_learning_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('enrolled', 'Qabul qilingan'), ('finished', 'Tugatgan'), ('canceled', 'Bekor qilingan')], default='enrolled', max_length=20),
        ),
    ]
