# Generated by Django 5.0.6 on 2026-07-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0021_shift_students_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, help_text="To'liq ismi", max_length=255, null=True),
        ),
    ]
