# Generated by Django 5.0.6 on 2026-07-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True),
        ),
    ]
