# Generated by Django 5.0.6 on 2026-07-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_user_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Superuser'), ('admin', 'Admin'), ('mechanic', 'Mexanik'), ('instructor', 'Instruktor'), ('coordinator', "O'qituvchi"), ('student', "O'quvchi")], default='coordinator', max_length=20),
        ),
    ]
