# Generated by Django 5.0.6 on 2026-07-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Qabul qilingan'), ('returned', 'Qaytarilgan'), ('paid', "To'langan"), ('bonus', 'Bonus')], default='accepted', max_length=20),
        ),
    ]
