# Generated by Django 5.0.6 on 2026-07-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Qabul qilingan'), ('returned', 'Qaytarilgan'), ('paid', "To'langan"), ('bonus', 'Bonus'), ('bank', 'Bank')], default='accepted', max_length=20),
        ),
    ]
