# Generated by Django 5.0.6 on 2026-07-22 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0026_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('full_name', models.CharField(help_text='Agent F.I.SH.', max_length=255)),
                ('phone', models.CharField(help_text='Telefon raqami', max_length=20, unique=True)),
                ('phone2', models.CharField(blank=True, help_text="Qo'shimcha telefon raqami", max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agentlar',
                'db_table': 'agent',
            },
        ),
        migrations.AddField(
            model_name='enrollment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='management.agent'),
        ),
    ]
