# Generated by Django 5.0.6 on 2026-07-24 11:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_agent_enrollment_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('holiday_name', models.CharField(help_text='Bayram / Dam olish kuni nomi', max_length=255)),
                ('start_date', models.DateField(help_text='Boshlanish sanasi')),
                ('end_date', models.DateField(help_text='Tugash sanasi')),
                ('note', models.TextField(blank=True, help_text="Qo'shimcha izoh", null=True)),
            ],
            options={
                'verbose_name': 'Bayram',
                'verbose_name_plural': 'Bayramlar',
                'db_table': 'holidays',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='working_days',
            field=models.PositiveIntegerField(blank=True, help_text='Ish kunlari soni (kategoriyadan olinadi)', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='working_weekends',
            field=models.CharField(choices=[('everyday', 'Har kuni (Mon-Sat)'), ('mon-wed-fri', 'Dushanba - Chorshanba - Juma (Mo-Wed-Fri)'), ('tue-wed-sat', 'Seshanba - Payshanba - Shanba (Tue-Thu-Sat)')], default='mon-wed-fri', help_text='Dars kunlari jadvali', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='management.agent'),
        ),
        migrations.AlterField(
            model_name='category',
            name='duration',
            field=models.PositiveIntegerField(default=68, help_text='Ish kunlari (masalan: 68)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='duration',
            field=models.FloatField(blank=True, help_text='Davomiyligi (oylar, masalan, 3.2 yoki 3.4)', null=True),
        ),
    ]
