# Generated by Django 5.0.6 on 2026-07-25 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_holidays_group_working_days_group_working_weekends_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('car_name', models.CharField(help_text='Avtomobil nomi va davlat raqami (masalan: Cobalt 01 A 777 AA)', max_length=255)),
                ('manufact_year', models.IntegerField(blank=True, help_text='Ishlab chiqarilgan yili (masalan: 2022)', null=True)),
                ('policy_date', models.DateField(blank=True, help_text="Sug'urta amal qilish muddati", null=True)),
                ('tech_inspection_date', models.DateField(blank=True, help_text="Texnik ko'rik muddati", null=True)),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
                'db_table': 'car',
                'ordering': ['car_name'],
            },
        ),
    ]
