# Generated by Django 5.0.6 on 2026-07-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'Mavjud'), ('repairing', "Ta'mirlashda"), ('not_available', 'Mavjud emas')], default='available', help_text='Avtomobil holati: available, repairing, not_available', max_length=20),
        ),
    ]
