# Generated by Django 5.0.6 on 2026-07-25 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_car_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('lesson_date', models.DateField(default=django.utils.timezone.now, help_text='Amaliy dars sanasi')),
                ('car', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_lessons', to='management.car')),
                ('instructor', models.ForeignKey(limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_lessons', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='driving_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amaliy Haydash Darsi',
                'verbose_name_plural': 'Amaliy Haydash Darslari',
                'db_table': 'driving_lessons',
                'ordering': ['-lesson_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('title', models.CharField(help_text='Bildirishnoma sarlavhasi', max_length=255)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Bildirishnoma sanasi')),
                ('note', models.TextField(blank=True, help_text='Batafsil izoh', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text="O'qilganlik holati")),
                ('status', models.CharField(choices=[('driving_lesson', 'Amaliy Haydash Darsi'), ('certificate_upload', 'Sertifikat Yuklash'), ('payment', "To'lov"), ('agent_payment', "Agent To'lovi")], default='driving_lesson', max_length=30)),
                ('user', models.ForeignKey(blank=True, help_text="Qabul qiluvchi (null bo'lsa adminlar uchun)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'db_table': 'notification',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
