# Generated by Django 5.0.6 on 2026-07-28 06:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_drivinglessons_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('name', models.CharField(help_text='Filial nomi', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Filial',
                'verbose_name_plural': 'Filiallar',
                'db_table': 'branch',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, help_text='Avtomobil rasmi', null=True, upload_to='cars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, help_text='Foydalanuvchi rasmi', null=True, upload_to='users/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='management.branch'),
        ),
        migrations.AddField(
            model_name='category',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='management.branch'),
        ),
        migrations.AddField(
            model_name='drivinglessons',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driving_lessons', to='management.branch'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='management.branch'),
        ),
        migrations.AddField(
            model_name='group',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='management.branch'),
        ),
        migrations.AddField(
            model_name='learningplace',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_places', to='management.branch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='management.branch'),
        ),
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='management.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='management.branch'),
        ),
    ]
