# Generated by Django 5.0.6 on 2026-07-28 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_branch_car_image_user_image_agent_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pass_img',
            field=models.FileField(blank=True, help_text='Pasport nusxasi / rasmi (faqat talabalar uchun)', null=True, upload_to='passports/'),
        ),
    ]
