# Generated by Django 5.0.6 on 2026-07-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0040_notification_target_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('enrolled', 'Faol'), ('finished', 'Tugatgan'), ('canceled', 'Bekor qilingan')], default='new', max_length=20),
        ),
    ]
