# Generated by Django 5.0.6 on 2026-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0041_alter_enrollment_status'),
    ]

    operations = [
        # Old data is free-text ("Mo-Wed-Fri" / "Tue-Thu-Sat" / "everyday" / NULL) which
        # isn't valid JSON, so it has to be rewritten to a JSON array of weekday indices
        # (0=Mon..5=Sat) before the column can be cast to jsonb below.
        migrations.RunSQL(
            sql="""
                UPDATE enrollment SET learning_days = CASE
                    WHEN learning_days = 'Mo-Wed-Fri' THEN '[0, 2, 4]'
                    WHEN learning_days = 'Tue-Thu-Sat' THEN '[1, 3, 5]'
                    WHEN learning_days = 'everyday' THEN '[0, 1, 2, 3, 4, 5]'
                    ELSE '[]'
                END;
            """,
            reverse_sql="""
                UPDATE enrollment SET learning_days = CASE
                    WHEN learning_days::jsonb = '[0, 2, 4]'::jsonb THEN 'Mo-Wed-Fri'
                    WHEN learning_days::jsonb = '[1, 3, 5]'::jsonb THEN 'Tue-Thu-Sat'
                    WHEN learning_days::jsonb = '[0, 1, 2, 3, 4, 5]'::jsonb THEN 'everyday'
                    ELSE NULL
                END;
            """,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='learning_days',
            field=models.JSONField(blank=True, default=list, help_text='Dars kunlari, Dushanba-Shanba: 0=Dushanba, 1=Seshanba, 2=Chorshanba, 3=Payshanba, 4=Juma, 5=Shanba'),
        ),
    ]
