# Generated by Django 5.0.6 on 2026-07-30 08:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0042_alter_enrollment_learning_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivinglessons',
            name='lesson_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Amaliy dars sanasi va vaqti'),
        ),
    ]
