# Generated by Django 5.0.6 on 2026-07-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0043_alter_drivinglessons_lesson_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carassignmenthistory',
            name='mileage_at_unassignment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carassignmenthistory',
            name='oil_change_date_at_unassignment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carassignmenthistory',
            name='oil_change_mileage_at_unassignment',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
