# Generated by Django 5.0.6 on 2026-07-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0044_carassignmenthistory_mileage_at_unassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate_added_date',
            field=models.DateTimeField(blank=True, help_text="Kursni tugatganlik sertifikati qo'shilgan sana", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='certificate_number',
            field=models.CharField(blank=True, help_text="Kursni tugatganlik sertifikati raqami (9 ta raqam). Bu imtihon sertifikati emas, faqat kursni tugatganlik sertifikati — qo'shilishi hech qanday holatni o'zgartirmaydi.", max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='certificate_series',
            field=models.CharField(blank=True, help_text='Kursni tugatganlik sertifikati seriyasi. Namuna: AB', max_length=2, null=True),
        ),
    ]
