# Generated by Django 5.0.6 on 2026-07-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0045_user_certificate_added_date_user_certificate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
