# Generated by Django 5.0.6 on 2026-07-31 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0046_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivinglessons',
            name='hours',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Avtodromda o'tkazilgan soatlar soni (faqat Avtodrom turi uchun, 1-6)", null=True),
        ),
        migrations.AddField(
            model_name='drivinglessons',
            name='lesson_type',
            field=models.CharField(choices=[('driving', 'Amaliy haydash'), ('autodrome', 'Avtodrom')], default='driving', max_length=20),
        ),
    ]
