# Generated by Django 5.0.6 on 2026-08-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0047_drivinglessons_hours_drivinglessons_lesson_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('qr_code', 'QR code'), ('transfer', "O'tkazma"), ('click', 'Click')], default='cash', max_length=20),
        ),
    ]
