# Generated by Django 5.0.6 on 2026-08-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0048_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('accepted', 'Qabul qilingan'), ('returned', 'Qaytarilgan'), ('paid', "To'langan"), ('bonus', 'Bonus'), ('bank', 'Bank'), ('bonus_teacher', 'Sertifikat bonusi')], default='accepted', max_length=20),
        ),
    ]
