# Generated by hand (rename, not remove+add — preserves existing FK data)

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0049_alter_payment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcertificate',
            old_name='instructor',
            new_name='coordinator',
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='coordinator',
            field=models.ForeignKey(
                blank=True,
                help_text="Sertifikatni yuklagan o'qituvchi",
                limit_choices_to={'role': 'coordinator'},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='uploaded_certificates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='bonus_payment',
            field=models.ForeignKey(
                blank=True,
                help_text="Ushbu sertifikat uchun o'qituvchiga to'langan bonus to'lovi (agar to'langan bo'lsa)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='certificate',
                to='management.payment',
            ),
        ),
    ]
