# Generated by Django 5.0.6 on 2026-08-02 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0050_rename_instructor_studentcertificate_coordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text="The admin/superuser who entered this payment record into the system — distinct from 'user', which means different things per status.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(help_text="Payment's counterpart per status: cashier who accepted/returned/banked it, the agent-bonus payout's cashier, or the teacher/instructor being paid.", on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
