# Generated by Django 5.0.6 on 2026-08-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0052_backfill_payment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='can_view_payments',
            field=models.BooleanField(blank=True, default=True, help_text="O'quvchi o'z to'lovlar tarixini ko'ra oladimi", null=True),
        ),
    ]
