# Generated by Django 5.0.6 on 2026-08-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0053_enrollment_can_view_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, help_text="Tug'ilgan sana (o'quvchilar uchun)", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, help_text='Instruktorlik guvohnomasi raqami (6 ta raqam)', max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='license_series',
            field=models.CharField(blank=True, help_text='Instruktorlik guvohnomasi seriyasi (2 ta harf). Namuna: AB', max_length=2, null=True),
        ),
    ]
