# Generated by Django 5.0.6 on 2026-08-02 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0054_user_birthdate_and_license_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='user',
            field=models.OneToOneField(blank=True, help_text="Agar bu agent aslida talaba olib kelgan o'qituvchi/instruktor bo'lsa, shu foydalanuvchiga bog'lanadi", limit_choices_to={'role__in': ['instructor', 'coordinator']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
