# Generated by Django 5.0.6 on 2026-08-03 06:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0055_agent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='click_check_image',
            field=models.FileField(blank=True, help_text="Click orqali to'langanda, to'lov cheki rasmi (ixtiyoriy)", null=True, upload_to='click_checks/'),
        ),
        migrations.CreateModel(
            name='AutodromeAccessGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('visits', models.PositiveSmallIntegerField(help_text='Necha marta avtodromga qayta borishga ruxsat berilgan')),
                ('start_date', models.DateField(help_text='Amal qilish boshlanish sanasi')),
                ('end_date', models.DateField(help_text='Amal qilish tugash sanasi')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autodrome_grants', to='management.branch')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autodrome_grants_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='autodrome_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Avtodrom qo'shimcha ruxsati",
                'verbose_name_plural': "Avtodrom qo'shimcha ruxsatlari",
                'db_table': 'autodrome_access_grant',
                'ordering': ['-created_at'],
            },
        ),
    ]
