# Generated by Django 5.0.6 on 2026-08-04 10:46

from django.db import migrations, models


def backfill_existing_as_excel_imported(apps, schema_editor):
    # Every enrollment that already exists the moment this field is added
    # predates the flag itself, and in this project's timeline that means
    # it came from the legacy Excel import — new enrollments created after
    # this migration (via the normal UI) keep the field's own False default.
    Enrollment = apps.get_model("management", "Enrollment")
    Enrollment.objects.update(excel_imported=True)


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0057_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='excel_imported',
            field=models.BooleanField(default=False, help_text="Excel fayl orqali import qilingan yozuv (shartnoma summasi bo'sh bo'lishi mumkin)"),
        ),
        migrations.RunPython(backfill_existing_as_excel_imported, migrations.RunPython.noop),
    ]
