# Generated by Django 5.0.6 on 2026-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0058_enrollment_excel_imported'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='director_full_name',
            field=models.CharField(blank=True, help_text="Filial rahbarining to'liq F.I.SH. (yo'l varaqasi va daftarcha kabi hujjatlarda ishlatiladi)", max_length=255, null=True),
        ),
    ]
