# Generated by Django 5.0.6 on 2026-08-06 14:53

import management.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0059_branch_director_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.FileField(blank=True, help_text='Avtomobil rasmi', null=True, upload_to='cars/', validators=[management.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='click_check_image',
            field=models.FileField(blank=True, help_text="Click orqali to'langanda, to'lov cheki rasmi (ixtiyoriy)", null=True, upload_to='click_checks/', validators=[management.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='studentcertificate',
            name='image',
            field=models.FileField(help_text='Sertifikat rasmi', upload_to='certificates/', validators=[management.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.FileField(blank=True, help_text='Foydalanuvchi rasmi', null=True, upload_to='users/', validators=[management.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pass_img',
            field=models.FileField(blank=True, help_text='Pasport nusxasi / rasmi (faqat talabalar uchun)', null=True, upload_to='passports/', validators=[management.validators.validate_image_or_pdf_file]),
        ),
    ]
