# Generated by Django 5.0.6 on 2026-08-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0060_alter_car_image_alter_payment_click_check_image_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='payment_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['method'], name='payment_method_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payment_created_at_idx'),
        ),
    ]
