# Generated by Django 5.0.6 on 2026-08-07 06:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0061_payment_add_status_method_created_at_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True, help_text="Qo'shimcha eslatmalar", null=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('last_row', models.PositiveIntegerField(default=0, help_text='Sheet row number the import last successfully finished at. 0 = never imported.')),
                ('last_file_hash', models.CharField(blank=True, help_text='SHA-256 of the most recently imported file, for reference only (not used for matching).', max_length=64)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_import_batches', to='management.branch')),
            ],
            options={
                'verbose_name': 'Excel import partiyasi',
                'verbose_name_plural': 'Excel import partiyalari',
                'db_table': 'excel_import_batch',
                'unique_together': {('original_filename', 'branch')},
            },
        ),
    ]
